version: 1
disable_existing_loggers: False

formatters:
  brief:
    format: '%(levelname)-8s - %(message)s'
  detailed:
    format: '%(asctime)s.%(msecs)03d %(levelname)-8s %(name)-15s %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  console:    
    class : logging.StreamHandler
    formatter: detailed
    level   : DEBUG
    stream  : ext://sys.stdout
  file_API:
    class : logging.handlers.RotatingFileHandler
    formatter: detailed
    level   : DEBUG
    filename: ./sapcon/logs/API.log
    maxBytes: 10485760 #10MB 10*1024*1024
    backupCount: 15
  file_RFC:
    class : logging.handlers.RotatingFileHandler
    formatter: detailed
    level   : DEBUG
    filename: ./sapcon/logs/RFC.log
    maxBytes: 10485760 #10MB 10*1024*1024
    backupCount: 15    
  file_LogsDeltaMananger:
    class : logging.handlers.RotatingFileHandler
    formatter: detailed
    level   : DEBUG
    filename: ./sapcon/logs/LogsDeltaManager.log
    maxBytes: 10485760 #10MB 10*1024*1024
    backupCount: 15    
  file_PersistenceMananger:
    class : logging.handlers.RotatingFileHandler
    formatter: detailed
    level   : DEBUG
    filename: ./sapcon/logs/PersistenceManager.log
    maxBytes: 10485760 #10MB 10*1024*1024
    backupCount: 15 
  file_SysAdmin:
    class : logging.handlers.RotatingFileHandler
    formatter: detailed
    level   : DEBUG
    filename: ./sapcon/logs/SystemAdmin.log
    maxBytes: 10485760 #10MB 10*1024*1024
    backupCount: 15     
  file_ABAPAuditLog:
    class : logging.handlers.RotatingFileHandler
    formatter: detailed
    level   : DEBUG
    filename: ./sapcon/logs/ABAPAuditLog.log
    maxBytes: 10485760 #10MB 10*1024*1024
    backupCount: 15       
  file_ABAPJobLog:
    class : logging.handlers.RotatingFileHandler
    formatter: detailed
    level   : DEBUG
    filename: ./sapcon/logs/ABAPJobLog.log
    maxBytes: 10485760 #10MB 10*1024*1024
    backupCount: 15       
  file_ABAPSpoolLog:
    class : logging.handlers.RotatingFileHandler
    formatter: detailed
    level   : DEBUG
    filename: ./sapcon/logs/ABAPSpoolLog.log
    maxBytes: 10485760 #10MB 10*1024*1024
    backupCount: 15         
  file_ABAPSpoolOutputLog:
    class : logging.handlers.RotatingFileHandler
    formatter: detailed
    level   : DEBUG
    filename: ./sapcon/logs/ABAPSpoolOutputLog.log
    maxBytes: 10485760 #10MB 10*1024*1024
    backupCount: 15             
  file_ABAPChangeDocsLog:
    class : logging.handlers.RotatingFileHandler
    formatter: detailed
    level   : DEBUG
    filename: ./sapcon/logs/ABAPChangeDocsLog.log
    maxBytes: 10485760 #10MB 10*1024*1024
    backupCount: 15         
  file_ABAPAppLog:
    class : logging.handlers.RotatingFileHandler
    formatter: detailed
    level   : DEBUG
    filename: ./sapcon/logs/ABAPAppLog.log
    maxBytes: 10485760 #10MB 10*1024*1024
    backupCount: 15         
  file_ABAPWorkflowLog:
    class : logging.handlers.RotatingFileHandler
    formatter: detailed
    level   : DEBUG
    filename: ./sapcon/logs/ABAPWorkflowLog.log
    maxBytes: 10485760 #10MB 10*1024*1024
    backupCount: 15    
  file_ABAPCRLog:
    class : logging.handlers.RotatingFileHandler
    formatter: detailed
    level   : DEBUG
    filename: ./sapcon/logs/ABAPCRLog.log
    maxBytes: 10485760 #10MB 10*1024*1024
    backupCount: 15             
  file_ABAPTableDataLog:
    class : logging.handlers.RotatingFileHandler
    formatter: detailed
    level   : DEBUG
    filename: ./sapcon/logs/ABAPTableDataLog.log
    maxBytes: 10485760 #10MB 10*1024*1024
    backupCount: 15                   
  file_ABAPLogFiles:
    class : logging.handlers.RotatingFileHandler
    formatter: detailed
    level   : DEBUG
    filename: ./sapcon/logs/ABAPLogFiles.log
    maxBytes: 10485760 #10MB 10*1024*1024
    backupCount: 15                  
  file_Root:
    class : logging.handlers.RotatingFileHandler
    formatter: detailed
    level   : DEBUG
    filename: ./sapcon/logs/root.log
    maxBytes: 10485760 #10MB 10*1024*1024
    backupCount: 15
  file_scheduler:
    class : logging.handlers.RotatingFileHandler
    formatter: detailed
    level   : DEBUG
    filename: ./sapcon/logs/scheduler.log
    maxBytes: 10485760 #10MB 10*1024*1024
    backupCount: 15   
  file_AbapTableExtractor:
    class : logging.handlers.RotatingFileHandler
    formatter: detailed
    level   : DEBUG
    filename: ./sapcon/logs/AbapTableExtractor.log
    maxBytes: 10485760 #10MB 10*1024*1024
    backupCount: 15         

root:
  level: DEBUG
  handlers: [file_Root]

loggers: 
  apscheduler:
    level: DEBUG
    handlers: [console, file_scheduler]
  AbapTableExtractor:    
    level   : DEBUG
    handlers: [console, file_AbapTableExtractor]    
  API:    
    level   : DEBUG
    handlers: [console, file_API]
  RFC:    
    level   : DEBUG
    handlers: [console, file_RFC]
  DeltaManager:
    level   : DEBUG
    handlers: [console, file_LogsDeltaMananger]
  Persistence:
    level   : DEBUG
    handlers: [console, file_PersistenceMananger]    
  SysAdmin:
    level   : DEBUG
    handlers: [console, file_SysAdmin]
  ABAPAuditLog:
    level   : DEBUG
    handlers: [console, file_ABAPAuditLog]
  ABAPJobLog:
    level   : DEBUG
    handlers: [console, file_ABAPJobLog]    
  ABAPSpoolLog:
    level   : DEBUG
    handlers: [console, file_ABAPSpoolLog]    
  ABAPSpoolOutputLog:
    level   : DEBUG
    handlers: [console, file_ABAPSpoolOutputLog]        
  ABAPChangeDocsLog:
    level   : DEBUG
    handlers: [console, file_ABAPChangeDocsLog]        
  ABAPAppLog:
    level   : DEBUG
    handlers: [console, file_ABAPAppLog]            
  ABAPWorkflowLog:
    level   : DEBUG
    handlers: [console, file_ABAPWorkflowLog]              
  ABAPCRLog:
    level   : DEBUG
    handlers: [console, file_ABAPCRLog]              
  ABAPTableDataLog:
    level   : DEBUG
    handlers: [console, file_ABAPTableDataLog]                      
  ABAPLogFiles:
    level   : DEBUG
    handlers: [console, file_ABAPLogFiles]              
