blank_issues_enabled: false
contact_links:
  - name: Seek guidance in the Net
    url: https://github.com/yourproject/community
    about: For queries unbound by templates, join our community discussions.
  - name: Direct Communique
    url: https://github.com/yourproject/contact
    about: For direct contact with the architects, use this channel.
