name: 🐛 Bug Report
description: Report anomalies in the code matrix
title: "[BUG]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: "## Bug Report - Data Stream Disruption\nDescribe the glitch in the digital tapestry that binds our code."

  - type: input
    id: description
    attributes:
      label: "Bug Description"
      description: "What aberration have you discovered in the grid?"
      placeholder: "Describe the anomaly..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: "Reproduction Steps"
      description: "Detail the path you took through the cyberspace that led you to this anomaly."
      placeholder: "1. Enter the command...\n2. Witness the divergence..."
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: "Environment"
      description: "In what realm of our digital world did you encounter this glitch?"
      placeholder: "InfoSec Blueprints version, OS, dependencies..."
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: "Additional Context"
      description: "Any other fragments of data or screenshots to aid our navigators?"
      placeholder: "Add any other context here..."

  - type: checkboxes
    id: terms
    attributes:
      label: "Code of Conduct"
      description: "I vow to uphold the digital ethos of our realm."
      options:
        - label: "I agree"
          required: true
