name: Documentation Discrepancy
description: Report anomalies or enhancements for the digital lexicon.
title: "[DOCS]: "
body:
  - type: markdown
    attributes:
      value: "In the sprawling digital landscape, documentation is the guiding light. Help us refine this beacon."
  - type: textarea
    id: what-needs-change
    attributes:
      label: What requires illumination?
      description: Detail the documentation segments that need refinement or correction.
      placeholder: "In the third paragraph of our virtual realm's guide, the code cipher seems amiss..."
    validations:
      required: true
  - type: textarea
    id: suggestions
    attributes:
      label: Proposed Enhancements
      description: "Your insights into the cryptic digital manuscripts."
      placeholder: "Consider rephrasing the command sequence to better reflect..."
    validations:
      required: false
