name: ✨ Feature Request
description: Propose enhancements to our digital realm
title: "[FEATURE]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: "## Feature Request - Digital Evolution\nWhat new capabilities shall we weave into the fabric of our code?"

  - type: input
    id: feature
    attributes:
      label: "Feature Description"
      description: "Describe the augmentation you envision."
      placeholder: "A detailed description of your proposed feature..."
    validations:
      required: true

  - type: textarea
    id: benefits
    attributes:
      label: "Benefits"
      description: "How does this enhancement enrich our digital ecosystem?"
      placeholder: "Explain the benefits..."
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: "Additional Context"
      description: "Any diagrams, prototypes, or additional information?"
      placeholder: "Add any other context or screenshots here..."

  - type: checkboxes
    id: terms
    attributes:
      label: "Code of Conduct"
      description: "I vow to uphold the digital ethos of our realm."
      options:
        - label: "I agree"
          required: true
