# GitHub Actions Workflow - InfoSec Blueprints
# In the sprawling digital metropolis of our project, this workflow is the pulse of our InfoSec Blueprints odyssey.
# It echoes the ethos of "Neuromancer", orchestrating our code in the vast cybernetic expanse.

name: InfoSec Blueprints

# Trigger the workflow on push events but only for the main branch
on:
  push:
    branches: [ main ]

# Jobs to be executed
jobs:
  build:

    # Running on a machine with the latest Ubuntu
    runs-on: ubuntu-latest

    steps:
    # Checking out our code into the world of GitHub Actions
    - uses: actions/checkout@v2

    # Running the "Hello World" script
    - name: Run a one-line script
      run: |
        echo "Echoing through the digital void..."
        echo "Hello World from the neon depths of InfoSec Blueprints!"

